name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install --global yarn
      - run: yarn install
      - run: cd packages/vite-plugin-story-canvas-source && yarn build
      - run: cd packages/icons && yarn build
      - run: cd packages/core && yarn build
      - run: cd packages/docs && yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: packages/docs/dist
